# Generated by Django 2.2.6 on 2019-10-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibonaccitest',
            old_name='latency',
            new_name='time_taken',
        ),
    ]
